export type SupportedLanguage = "pt-BR" | "en" | "es";

export type CanonicalStatus =
  | "PRONTO"
  | "PARCIALMENTE PRONTO"
  | "NÃO PRONTO"
  | "EXCEÇÃO APROVADA"
  | "EXCEÇÃO NÃO RECOMENDADA";

export const DEFAULT_LANGUAGE: SupportedLanguage = "pt-BR";

export const SUPPORTED_LANGUAGES: SupportedLanguage[] = ["pt-BR", "en", "es"];

export const LANGUAGE_PROMPT_OPTIONS = [
  { name: "Português (Brasil)", value: "pt-BR" as const },
  { name: "English", value: "en" as const },
  { name: "Español", value: "es" as const },
];

export type SectionKey =
  | "spec.classification"
  | "spec.objective"
  | "spec.readinessStatus"
  | "spec.confirmedDecisions"
  | "spec.pendingDecisions"
  | "plan.finalDecision"
  | "plan.validatedInputs"
  | "plan.acceptanceCriteria"
  | "plan.exceptionMode";

export type FieldKey = "spec.workType" | "spec.riskLevel" | "spec.triageConfidence";

const SECTION_HEADINGS: Record<SectionKey, Record<SupportedLanguage, string>> = {
  "spec.classification": {
    "pt-BR": "Classificação RTA",
    en: "RTA Classification",
    es: "Clasificación RTA",
  },
  "spec.objective": {
    "pt-BR": "Objetivo",
    en: "Objective",
    es: "Objetivo",
  },
  "spec.readinessStatus": {
    "pt-BR": "Status de prontidão",
    en: "Readiness status",
    es: "Estado de preparación",
  },
  "spec.confirmedDecisions": {
    "pt-BR": "Decisões confirmadas",
    en: "Confirmed decisions",
    es: "Decisiones confirmadas",
  },
  "spec.pendingDecisions": {
    "pt-BR": "Decisões pendentes",
    en: "Pending decisions",
    es: "Decisiones pendientes",
  },
  "plan.finalDecision": {
    "pt-BR": "Decisão final",
    en: "Final decision",
    es: "Decisión final",
  },
  "plan.validatedInputs": {
    "pt-BR": "Insumos validados",
    en: "Validated inputs",
    es: "Insumos validados",
  },
  "plan.acceptanceCriteria": {
    "pt-BR": "Critérios de aceite finais",
    en: "Final acceptance criteria",
    es: "Criterios de aceptación finales",
  },
  "plan.exceptionMode": {
    "pt-BR": "Modo de exceção",
    en: "Exception mode",
    es: "Modo de excepción",
  },
};

const FIELD_LABELS: Record<FieldKey, Record<SupportedLanguage, string>> = {
  "spec.workType": {
    "pt-BR": "Tipo de trabalho",
    en: "Work type",
    es: "Tipo de trabajo",
  },
  "spec.riskLevel": {
    "pt-BR": "Nível de risco",
    en: "Risk level",
    es: "Nivel de riesgo",
  },
  "spec.triageConfidence": {
    "pt-BR": "Confiança da triagem",
    en: "Triage confidence",
    es: "Confianza de la clasificación",
  },
};

const ARTIFACT_LABELS: Record<
  "spec" | "plan" | "tasks",
  Record<SupportedLanguage, string>
> = {
  spec: {
    "pt-BR": "Especificação consolidada",
    en: "Consolidated specification",
    es: "Especificación consolidada",
  },
  plan: {
    "pt-BR": "Plano técnico",
    en: "Technical plan",
    es: "Plan técnico",
  },
  tasks: {
    "pt-BR": "Checklist de implementação",
    en: "Implementation checklist",
    es: "Checklist de implementación",
  },
};

const EXPORT_LABELS: Record<
  SupportedLanguage,
  {
    title: string;
    metadata: string;
    task: string;
    squad: string;
    ide: string;
    exportedAt: string;
    specSection: string;
    planSection: string;
    tasksSection: string;
    appendix: string;
    emptySection: string;
    notFilled: string;
    footer: string;
  }
> = {
  "pt-BR": {
    title: "Spec-Kit Input — RTA / AI Spec Protocol",
    metadata: "Metadados",
    task: "Tarefa",
    squad: "Squad",
    ide: "IDE",
    exportedAt: "Exportado em",
    specSection: "Especificação consolidada (spec.md)",
    planSection: "Plano técnico (plan.md)",
    tasksSection: "Checklist de implementação (tasks.md)",
    appendix: "Anexo — Artefatos completos",
    emptySection: "_(sem conteúdo preenchido)_",
    notFilled: "_(não preenchido)_",
    footer:
      "_Gerado por spec-protocol export. Use como insumo para GitHub Spec-Kit._",
  },
  en: {
    title: "Spec-Kit Input — RTA / AI Spec Protocol",
    metadata: "Metadata",
    task: "Task",
    squad: "Squad",
    ide: "IDE",
    exportedAt: "Exported at",
    specSection: "Consolidated specification (spec.md)",
    planSection: "Technical plan (plan.md)",
    tasksSection: "Implementation checklist (tasks.md)",
    appendix: "Appendix — Full artifacts",
    emptySection: "_(no content filled)_",
    notFilled: "_(not filled)_",
    footer:
      "_Generated by spec-protocol export. Use as input for GitHub Spec-Kit._",
  },
  es: {
    title: "Spec-Kit Input — RTA / AI Spec Protocol",
    metadata: "Metadatos",
    task: "Tarea",
    squad: "Squad",
    ide: "IDE",
    exportedAt: "Exportado en",
    specSection: "Especificación consolidada (spec.md)",
    planSection: "Plan técnico (plan.md)",
    tasksSection: "Checklist de implementación (tasks.md)",
    appendix: "Anexo — Artefactos completos",
    emptySection: "_(sin contenido completado)_",
    notFilled: "_(sin completar)_",
    footer:
      "_Generado por spec-protocol export. Use como insumo para GitHub Spec-Kit._",
  },
};

const CONTEXT_LABELS: Record<
  SupportedLanguage,
  {
    title: string;
    generatedBy: string;
    skillSection: string;
    entryPoint: string;
    forArtifact: string;
    filesSection: string;
    targetArtifact: string;
    otherArtifacts: string;
    instructionSection: string;
    instructionBody: string[];
    copyOutput: string;
    afterSection: string;
    validateWhenReady: string;
    allFilled: string;
    nextValidate: string;
    skillHints: {
      specNoClassification: string;
      specWithClassification: string;
      plan: string;
      tasks: string;
    };
  }
> = {
  "pt-BR": {
    title: "Roteiro RTA",
    generatedBy: "Gerado por spec-protocol-cli — use na IDE com skills RTA",
    skillSection: "1. Skill recomendada",
    entryPoint: "Ponto de entrada",
    forArtifact: "Para este artefato",
    filesSection: "2. Arquivos a referenciar com @",
    targetArtifact: "Artefato alvo",
    otherArtifacts: "Outros artefatos já preenchidos",
    instructionSection: "3. Instrução",
    instructionBody: [
      "Cole o card do Jira no chat. Invoque a skill RTA indicada acima.",
      "A skill orienta análise, preserva decisões já registradas e sugere conteúdo copiável para o artefato.",
    ],
    copyOutput: "Copie/refine a saída em `{artifact}`.",
    afterSection: "4. Depois",
    validateWhenReady: "(quando spec.md e plan.md estiverem OK)",
    allFilled: "Todos os artefatos estão preenchidos!",
    nextValidate: "Próximo passo: spec-protocol validate",
    skillHints: {
      specNoClassification: "@rta-triagem (spec.md ainda sem classificação)",
      specWithClassification:
        "@rta-analise → @rta-dor (spec.md já tem classificação)",
      plan: "@rta-plan (somente se spec.md estiver PRONTO ou EXCEÇÃO APROVADA)",
      tasks: "@rta-plan (somente após plan.md e spec.md prontos)",
    },
  },
  en: {
    title: "RTA Guide",
    generatedBy: "Generated by spec-protocol-cli — use in IDE with RTA skills",
    skillSection: "1. Recommended skill",
    entryPoint: "Entry point",
    forArtifact: "For this artifact",
    filesSection: "2. Files to reference with @",
    targetArtifact: "Target artifact",
    otherArtifacts: "Other completed artifacts",
    instructionSection: "3. Instruction",
    instructionBody: [
      "Paste the Jira card in chat. Invoke the RTA skill indicated above.",
      "The skill guides analysis, preserves recorded decisions, and suggests copyable content for the artifact.",
    ],
    copyOutput: "Copy/refine the output into `{artifact}`.",
    afterSection: "4. Next",
    validateWhenReady: "(when spec.md and plan.md are OK)",
    allFilled: "All artifacts are filled!",
    nextValidate: "Next step: spec-protocol validate",
    skillHints: {
      specNoClassification: "@rta-triagem (spec.md has no classification yet)",
      specWithClassification:
        "@rta-analise → @rta-dor (spec.md already classified)",
      plan: "@rta-plan (only if spec.md is READY or EXCEPTION APPROVED)",
      tasks: "@rta-plan (only after plan.md and spec.md are ready)",
    },
  },
  es: {
    title: "Guía RTA",
    generatedBy:
      "Generado por spec-protocol-cli — use en la IDE con skills RTA",
    skillSection: "1. Skill recomendada",
    entryPoint: "Punto de entrada",
    forArtifact: "Para este artefacto",
    filesSection: "2. Archivos a referenciar con @",
    targetArtifact: "Artefacto objetivo",
    otherArtifacts: "Otros artefactos ya completados",
    instructionSection: "3. Instrucción",
    instructionBody: [
      "Pegue la tarjeta de Jira en el chat. Invoque la skill RTA indicada arriba.",
      "La skill orienta el análisis, preserva decisiones registradas y sugiere contenido copiable para el artefacto.",
    ],
    copyOutput: "Copie/refine la salida en `{artifact}`.",
    afterSection: "4. Después",
    validateWhenReady: "(cuando spec.md y plan.md estén OK)",
    allFilled: "¡Todos los artefactos están completados!",
    nextValidate: "Próximo paso: spec-protocol validate",
    skillHints: {
      specNoClassification:
        "@rta-triagem (spec.md aún sin clasificación)",
      specWithClassification:
        "@rta-analise → @rta-dor (spec.md ya tiene clasificación)",
      plan: "@rta-plan (solo si spec.md está LISTO o EXCEPCIÓN APROBADA)",
      tasks: "@rta-plan (solo después de plan.md y spec.md listos)",
    },
  },
};

export function resolveLanguage(value: unknown): SupportedLanguage {
  if (value === "pt-BR" || value === "en" || value === "es") {
    return value;
  }
  return DEFAULT_LANGUAGE;
}

export function getArtifactLabel(
  id: "spec" | "plan" | "tasks",
  language: SupportedLanguage = DEFAULT_LANGUAGE,
): string {
  return ARTIFACT_LABELS[id][language];
}

export function getExportLabels(language: SupportedLanguage = DEFAULT_LANGUAGE) {
  return EXPORT_LABELS[language];
}

export function getContextLabels(language: SupportedLanguage = DEFAULT_LANGUAGE) {
  return CONTEXT_LABELS[language];
}

export function getSectionHeadings(key: SectionKey): string[] {
  const labels = SECTION_HEADINGS[key];
  return SUPPORTED_LANGUAGES.map((lang) => labels[lang]);
}

export function getFieldLabels(key: FieldKey): string[] {
  const labels = FIELD_LABELS[key];
  return SUPPORTED_LANGUAGES.map((lang) => labels[lang]);
}

export function findSectionContent(
  content: string,
  heading: string,
): string | null {
  const escaped = heading.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const match = content.match(
    new RegExp(`^## ${escaped}\\s*\\n([\\s\\S]*?)(?=^## |(?![\\s\\S]))`, "m"),
  );
  return match ? match[1] : null;
}

export function getSectionTextByKey(
  content: string,
  key: SectionKey,
  options: { stripPlaceholders?: boolean } = {},
): string {
  const strip = options.stripPlaceholders ?? true;
  for (const heading of getSectionHeadings(key)) {
    const raw = findSectionContent(content, heading);
    if (raw !== null) {
      return strip ? stripPlaceholders(raw) : stripComments(raw);
    }
  }
  return "";
}

export function getFieldValueByKey(section: string, key: FieldKey): string {
  for (const field of getFieldLabels(key)) {
    const value = getFieldValue(section, field);
    if (value) return value;
  }
  return "";
}

function getFieldValue(section: string, field: string): string {
  const escaped = field.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const match = section.match(
    new RegExp(`^-\\s*${escaped}:[ \\t]*([^\\n]+)$`, "mi"),
  );
  const value = stripPlaceholders(match?.[1] ?? "").trim();
  if (
    !value ||
    value.includes("/") ||
    (value.includes("[") && !/^\[(CRÍTICO|RISCO|HIPÓTESE|OBSERVAÇÃO)\]/i.test(value)) ||
    value.includes("...")
  ) {
    return "";
  }
  return value;
}

export function normalizeStatus(value: string): CanonicalStatus | "" {
  const status = stripPlaceholders(value).toUpperCase();

  if (
    status.includes("EXCEÇÃO APROVADA") ||
    status.includes("EXCEPTION APPROVED") ||
    status.includes("EXCEPCIÓN APROBADA")
  ) {
    return "EXCEÇÃO APROVADA";
  }

  if (
    status.includes("EXCEÇÃO NÃO RECOMENDADA") ||
    status.includes("EXCEPTION NOT RECOMMENDED") ||
    status.includes("EXCEPCIÓN NO RECOMENDADA")
  ) {
    return "EXCEÇÃO NÃO RECOMENDADA";
  }

  if (
    status.includes("PARCIALMENTE PRONTO") ||
    status.includes("PARTIALLY READY") ||
    status.includes("PARCIALMENTE LISTO")
  ) {
    return "PARCIALMENTE PRONTO";
  }

  if (
    status.includes("NÃO PRONTO") ||
    status.includes("NOT READY") ||
    status.includes("NO LISTO")
  ) {
    return "NÃO PRONTO";
  }

  if (
    (status.includes("PRONTO") ||
      status.includes("READY") ||
      /\bLISTO\b/.test(status)) &&
    !status.includes("PARCIAL") &&
    !status.includes("PARTIALLY") &&
    !status.includes("NÃO") &&
    !status.includes("NOT") &&
    !status.includes("NO LISTO")
  ) {
    return "PRONTO";
  }

  return "";
}

export function hasRealText(value: string): boolean {
  const text = stripPlaceholders(value).trim();
  return text.length > 0 && text !== "...";
}

export function stripPlaceholders(value: string): string {
  return stripComments(value)
    .replace(/\[(?!CRÍTICO|RISCO|HIPÓTESE|OBSERVAÇÃO|CRITICO)[^\]]+\]/gi, "")
    .replace(/\.\.\./g, "")
    .trim();
}

function stripComments(value: string): string {
  return value.replace(/<!--[\s\S]*?-->/g, "").trim();
}

export function hasSpecClassification(specContent: string | null): boolean {
  if (!specContent) return false;

  for (const lang of SUPPORTED_LANGUAGES) {
    const typeLabel = FIELD_LABELS["spec.workType"][lang];
    const riskLabel = FIELD_LABELS["spec.riskLevel"][lang];
    const type = specContent
      .match(new RegExp(`${typeLabel}:\\s*([^\\n<]+)`, "i"))?.[1]
      ?.trim();
    const risk = specContent
      .match(new RegExp(`${riskLabel}:\\s*([^\\n<]+)`, "i"))?.[1]
      ?.trim();
    if (type && risk) return true;
  }

  return false;
}

export function buildSkillLanguageInstruction(
  language: SupportedLanguage,
): string {
  if (language === "pt-BR") {
    return "";
  }

  const languageName = language === "en" ? "English" : "Español";
  return [
    "## Language / Idioma",
    "",
    `Respond and use labels in **${languageName}** (config: language=${language}).`,
    "Keep technical names unchanged: `@rta-*`, `spec.md`, `plan.md`, `tasks.md`.",
    "Keep taxonomy tags unchanged: `[CRÍTICO]`, `[RISCO]`, `[HIPÓTESE]`, `[OBSERVAÇÃO]`.",
    "",
  ].join("\n");
}

export function injectSkillLanguageInstruction(
  content: string,
  language: SupportedLanguage,
): string {
  const instruction = buildSkillLanguageInstruction(language);
  if (!instruction) return content;

  const frontmatterMatch = content.match(/^---\n[\s\S]*?\n---\n/);
  if (frontmatterMatch) {
    const rest = content.slice(frontmatterMatch[0].length);
    if (rest.includes("## Language / Idioma")) {
      return content;
    }
    return `${frontmatterMatch[0]}${instruction}${rest}`;
  }

  return `${instruction}${content}`;
}
